### ISSUE TITLE
Mac build support

### ISSUE THREAD

**Issue by matejsp** [rust-vmm/vhost#110]
Unable to build on mac Monterey 12.2.1.  Any chance to get around this?

```
➜  virtiofsd git:(main) cargo build --release
   Compiling vhost v0.3.0
   Compiling futures-executor v0.3.19
   Compiling structopt v0.3.26
error[E0432]: unresolved import `vmm_sys_util::eventfd`
  --> /Users/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/vhost-0.3.0/src/backend.rs:16:19
   |
16 | use vmm_sys_util::eventfd::EventFd;
   |                   ^^^^^^^ could not find `eventfd` in `vmm_sys_util`

error[E0432]: unresolved import `vmm_sys_util::sock_ctrl_msg`
  --> /Users/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/vhost-0.3.0/src/vhost_user/connection.rs:18:19
   |
18 | use vmm_sys_util::sock_ctrl_msg::ScmSocket;
   |                   ^^^^^^^^^^^^^ could not find `sock_ctrl_msg` in `vmm_sys_util`

   Compiling futures v0.3.19
error[E0599]: no method named `send_with_fds` found for struct `UnixStream` in the current scope
   --> /Users/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/vhost-0.3.0/src/vhost_user/connection.rs:142:19
    |
142 |         self.sock.send_with_fds(iovs, rfds).map_err(Into::into)
    |                   ^^^^^^^^^^^^^ method not found in `UnixStream`

error[E0599]: no method named `recv_with_fds` found for struct `UnixStream` in the current scope
   --> /Users/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/vhost-0.3.0/src/vhost_user/connection.rs:317:45
    |
317 |         let (bytes, _) = unsafe { self.sock.recv_with_fds(&mut iovs, &mut [])? };
    |                                             ^^^^^^^^^^^^^ method not found in `UnixStream`

error[E0599]: no method named `recv_with_fds` found for struct `UnixStream` in the current scope
   --> /Users/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/vhost-0.3.0/src/vhost_user/connection.rs:349:38
    |
349 |         let (bytes, fds) = self.sock.recv_with_fds(iovs, &mut fd_array)?;
    |                                      ^^^^^^^^^^^^^ method not found in `UnixStream`

Some errors have detailed explanations: E0432, E0599.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `vhost` due to 5 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by jiangliu** [comment]
We need to find macos counterparts for send fd with UDS and eventfd:)

**Comment by slp** [comment]
Funny, right now I'm working on implementing macOS support on `vmm-sys-util` (which will enable `vhost` and `vhost-user-backend` to work on it too). Sending ancillary data (i.e. for sending fds) is supported on macOS, so it's just a matter of including the traits. As for `eventfd` and `epoll`, I'm emulating the first with `pipefd` and the second with `kqueue`. They aren't semantically identical, but they're close enough to allow daemons consuming `vhost-user-backend` to work properly.

**Comment by jiangliu** [comment]
The `vmm_sys_util::sock_ctrl_msg` related issues are solved by enhancing the vmm_sys_util, but the EventFd is problematic.

**Comment by jiangliu** [comment]
> Funny, right now I'm working on implementing macOS support on `vmm-sys-util` (which will enable `vhost` and `vhost-user-backend` to work on it too). Sending ancillary data (i.e. for sending fds) is supported on macOS, so it's just a matter of including the traits. As for `eventfd` and `epoll`, I'm emulating the first with `pipefd` and the second with `kqueue`. They aren't semantically identical, but they're close enough to allow daemons consuming `vhost-user-backend` to work properly.

I have done a quick poc for sock_ctrl_msg:)

**Comment by stefano-garzarella** [comment]
@slp @jiangliu any plan on working on this?

If you have some PoC to share, maybe this could become a good first issue for some Mac user.
